### ISSUE TITLE
Added your code to Mini-Meters applet

### ISSUE THREAD

**Issue by corykim** [brandonschabell/daskeyboard-applet-gpu-usage#1]
I've added this meter to my Mini-Meters applet:

https://github.com/corykim/daskeyboard-applet--mini-meters/tree/feature/nvidia-gpu

Can you check it out? I don't have an nVidia GPU so I can't test it.

**Comment by brandonschabell** [comment]
Absolutely! I'll check it out when I get home from work tonight.
