### ISSUE TITLE
Issue Displaying GPU usage

### ISSUE THREAD

**Issue by hernandeztimothy15** [brandonschabell/daskeyboard-applet-gpu-usage#3]
Error: command cannot be executed. Please read documentation.

This is all i'm getting. I have the Nvidia software installed. Could you help me with this?

**Comment by brandonschabell** [comment]
@hernandeztimothy15
What operating system are you running?

Could you open up a terminal and run `nvidia-smi` and paste the results? Thanks!

**Comment by hernandeztimothy15** [comment]
Sorry, I should know better to include this info. I'm on windows. Does this applet only work on linux?

**Comment by brandonschabell** [comment]
@hernandeztimothy15 
It will work with Windows, it just may require some extra setup that linux handles for you when you install the Nvidia driver.

1. Find your Nvidia "NVSMI" directory. For me, it was installed here: `C:\Program Files\NVIDIA Corporation\NVSMI`
2. Add this directory to your PATH variable.
3. Test that this worked by opening a terminal and running `nvidia-smi`.
4. Fully restart the DasKeyboard application (a full computer restart may be necessary.)

It should now work correctly. Let me know if that helps!

**Comment by hernandeztimothy15** [comment]
@brandonschabell This worked! Thanks so much

**Comment by fredericoabraham** [comment]
I had the same issue and solved it using this report. A suggestion: to include this in the applet documentation. I couldn't figure out what "NVIDIA Client Software" meant :)

Thanks

**Comment by ScholliYT** [comment]
Jep, "NVIDIA Client Software" is a bit unspecific.

**Comment by brandonschabell** [comment]
@ScholliYT Thanks for the PR!
